apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: object-store
spec:
  retentionPolicy: "${barman_retention_policy}"
  configuration:
    destinationPath: s3://${s3_bucket}/
    s3Credentials:
      accessKeyId:
        name: aws-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: aws-creds
        key: ACCESS_SECRET_KEY
      sessionToken:
        name: aws-creds
        key: ACCESS_SESSION_TOKEN
    wal:
      compression: gzip
      encryption: AES256
