apiVersion: v1
data:
  password: dU4zaTFIaDBiWWJDYzRUeVZBYWNCaG1TemdxdHpxeG1PVmpBbjBRSUNoc0pyU211OVBZMmZ3MnE4RUtLTHBaOQ==
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  name: cluster-example-superuser
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: $cluster_name
spec:
  instances: 2
  imageName: "$postgres_major_upgrade_image"
  #imagePullPolicy: Never

  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: $barman_object_name
  enableSuperuserAccess: true

  # Reduce the frequency of standby HA slots updates to once every 5 minutes
  replicationSlots:
    highAvailability:
      enabled: true
    #updateInterval: 300

  postgresql:
    synchronous:
      method: any
      number: 1
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
    pg_hba:
      - host replication all all trust
      - hostssl replication all all trust
      - hostssl replication streaming_replica all cert
      - host all all 0.0.0.0/0 md5

  storage:
    size: $postgres_storage
  walStorage:
    size: $postgres_wal_storage
  tablespaces:
  - name: idxtbs
    storage:
      size: $postgres_idx_storage
  - name: tmptbs
    temporary: true
    storage:
      size: $postgres_tmp_storage

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      memory: "${postgres_memory}"
      cpu: "${postgres_cpu}"
    limits:
      memory: "${postgres_max_memory}"
      cpu: "${postgres_max_cpu}"

  #affinity:
  #  nodeSelector:
  #    workload: dc1
